filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

# processors:
#   - add_cloud_metadata: ~
#   - add_docker_metadata: ~


output.elasticsearch:
  #hosts: ["http://10.22.157.147:9200"]
  hosts: ["https://elasticsearch-elastic-rsyslog.apps.ocpprod.pjedomex.gob.mx:443"]
  # username: "elastic"
  # password: "<password>"
  # If using Elasticsearch's default certificate
  # ssl.ca_trusted_fingerprint: "<es cert fingerprint>"
  ssl.verification_mode: none
setup.kibana:
  #host: "http://10.22.157.147:5601"
  host: "https://kibana-elastic-rsyslog.apps.ocpprod.pjedomex.gob.mx:443"
  ssl.verification_mode: none
